services:

  db:
    image: postgres:15
    container_name: postgres-db
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - feedback-net
    restart: always

  backend:
    build: ./backend
    container_name: feedback-backend
    env_file: .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - feedback-net
    restart: always

  frontend:
    build: ./frontend
    container_name: feedback-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - feedback-net
    restart: always

volumes:
  pgdata:

networks:
  feedback-net:
    driver: bridge